/** PRD 第四章：弹窗与提示文案全集（合规改写，无赌博词汇）。代码统一引用本表，禁止散落硬编码。 */
export const TEXTS = {
    boxShake: '天地仙缘汇聚，静待揭晓',
    boxNormal: '获得些许修为，稳步修行',
    boxRare: '天降机缘，灵根增益！',
    boxBreakthroughChance: '感应到突破契机，可尝试冲击下一境界！',
    boxDisaster: '心魔侵扰，修为受损。',
    keepReward: '收下本次所得，暂作休整',
    seekAgain: '继续探寻仙缘，再试一次',
    seekLimit: '今日求索次数已用尽，先休整',
    rainOpen: '天道降下灵雨，把握机缘，躲避劫扰',
    rainImmortal: '完美接引灵雨，道心稳固！',
    breakthroughSuccess: (realm: string) => `境界晋升，踏入【${realm}】！`,
    breakthroughFail: '心魔干扰，突破未果，修为受损。',
    pityTriggered: '天道眷顾，获得稀有机缘。',
    lingshiNotEnough: '灵石不足，可观看广告获取灵石',
    lingshiAidRemain: (n: number, total: number) => `今日灵石救济剩余 ${n}/${total} 次`,
    lingshiAidExhausted: '今日救济次数已用尽，明日再来',
    rainTip: '滑动操控角色，接引灵雨，规避劫扰',
    quitRainConfirm: '退出则本次突破终止，机缘将受损，确定退出？',
    doubleXiuweiBtn: '修为加倍',
    protectBtn: '渡劫护道',
    purifyBtn: '净化劫雨',
    dailyGiftBtn: '每日仙缘',
    adSimTitle: '模拟激励广告',
    probabilityPublic: '概率公示',
    realmMax: '已达化神大圆满，前路自在心中',
    // 灵根图鉴（PRD 页面5）
    collectionHint: '收集灵根碎片，解锁道体外观',
    collectionCompose: '合 成',
    collectionComposed: '已解锁',
    collectionLocked: '未解锁',
    // 仙府商店（PRD 页面6）
    shopIapNotice: '内购功能审核中，暂未开放',
    shopIapOnlyVisual: '所有外观仅视觉效果，不改变修行概率',
    shopBuyBtn: '购 买',
    shopUnavailable: '暂未开放',
    // 设置（PRD 页面7）
    settingsSound: '音效',
    settingsBgm: '背景音乐',
    settingsProbability: '概率公示',
    settingsUserAgreement: '用户协议',
    settingsPrivacy: '隐私政策',
    probabilityTitle: '概率公示',
    agreementTitle: '用户协议',
    privacyTitle: '隐私政策',
    agreementPending: '正式协议文本上线前由运营补充（抖音审核必需）。',
    privacyPending: '正式隐私政策文本上线前由运营补充（抖音审核必需）。',
    // M7 交互深化（数值假设 #20–#26）
    resonateHint: '按住蓄力，光标居中时松手可引灵气共鸣',
    resonatePlainHint: '快速点击则直接开启',
    resonateSuccess: '灵气共鸣！所得增幅一成五',
    resonateSkip: '直接开启',
    chargeTitle: '引灵入匣',
    tripleTitle: '圆满三连',
    tripleHint: '依序点亮灵光符文，可获得天道赠礼',
    tripleSkip: '跳过',
    tripleLayer: (n: number) => `圆满 ×${n}`,
    tripleFull: '修行圆满，天道赠礼！',
    waveYunyu: '蕴雨 · 天地初霁',
    waveLingchao: '灵雨潮 · 机缘暴涨',
    waveJieyun: '劫云压顶 · 谨慎走位',
    comboFloat: (n: number) => `连击 ×${n}`,
    magnetBtn: '聚灵咒',
    magnetActive: '聚灵生效中',
    magnetUsed: '本局聚灵咒已用完',
    scoreLine: (score: number, combo: number) => `渡劫评分 ${score} · 最大连击 ×${combo}`,
    perfectStars: '★ ★ ★',
    // M8 修行日常（数值假设 #27–#29）
    questPageTitle: '修行任务',
    questActivity: (n: number) => `活跃度 ${n}/100`,
    questDone: '已完成',
    questChestClaim: '领 取',
    questChestClaimed: '已 领',
    questChestLocked: (at: number) => `需 ${at} 活跃度`,
    questRewardTicket: '修真宝盒券 ×1',
    illusionTitle: '心魔幻境',
    illusionOpen: '幻由心生，道心不灭——斩尽心魔',
    illusionTip: '15 秒强化灵雨：无清雨、劫雨更疾。得分越高，天道赏赐越厚',
    illusionEnter: '进入幻境',
    illusionEnterAd: '观广告 · 再战一局',
    illusionNone: '今日幻境次数已用尽，明日再来',
    illusionScoreLine: (score: number, best: number) => `幻境得分 ${score} · 今日最佳 ${best}`,
    illusionNoTier: '未达奖励档位（需 60 分），再接再厉',
    illusionTierReward: (t: string) => `达成【${t}】，天道赏赐：`,
    expeditionPageTitle: '云游历练',
    expeditionIdle: (n: number, total: number) => `今日剩余 ${total - n}/${total} 次`,
    expeditionExhausted: '今日历练已用尽，明日再来',
    expeditionRunning: '历练进行中…',
    expeditionComplete: '历练归来 · 有所见闻',
    expeditionRecall: '立即召回 · 广告',
    expeditionRecallHint: (m: number) => `${m} 分钟后可召回`,
    expeditionChoose: '你会如何抉择？',
    expeditionDisaster: '遭遇不测，修为受损',
    expeditionGo: '出 发',
    boxTicketBtn: '券 开 启',
    // M9a 论道与成就
    ludaoPageTitle: '论 道',
    ludaoTabRank: '排行',
    ludaoTabIllusion: '幻境',
    ludaoTabAchieve: '成就',
    rankRealmName: '境界榜',
    rankIllusionName: '幻境周榜',
    rankTribName: '渡劫评分榜',
    rankEmpty: '广结道友，共赴大道',
    rankYou: (v: string) => `你　　${v}`,
    rankGoal: (v: string) => `目标　${v}`,
    rankGoalLine: (name: string, v: string) => `${name}　${v}`,
    achieveClaim: '领 取',
    achieveClaimed: '已 领',
    achieveNew: (name: string) => `成就达成 · ${name}`,
    // M9c 收尾（PRD 2.4 分享 / 境界外观展示）
    shareBreakthrough: (realm: string) => `渡劫成功！我已踏入【${realm}】境，道友请留步~`,
    shareRealmUnlock: (realm: string) => `我在《凡人开仙缘》的道行已达【${realm}】，快来一起修仙！`,
    shareUnavailable: '分享功能仅在抖音端可用',
    realmLookTitle: '境界外观',
    realmLookReached: '当前境界 · 已解锁',
    realmLookLocked: (r: string) => `突破至【${r}】境解锁`,
    // M11 捏人开局（#32）
    profileTitle: '拜 入 仙 门',
    profileHint: '择一道体，取一道号，此生修行皆以此为凭',
    profileMale: '男 修',
    profileFemale: '女 修',
    profileNameHint: '道号（2~6 字）',
    profileRandomName: '随机道号',
    profileConfirm: '踏 入 仙 途',
    profileNameInvalid: '道号需 2~6 个字',
    // M11 攻防属性（#33）
    statAtk: '攻击',
    statDef: '防御',
    statPower: '战力',
    forgingTitle: '锻体',
    forgingLevel: (lv: number) => `锻体 ${lv} 重`,
    forgingMax: '锻体已至圆满',
    // M11 法器阁（#34）
    weaponTitle: '法 器 阁',
    weaponOwned: '已佩',
    weaponEquipped: '当前佩用',
    weaponBuy: '购 入',
    weaponLocked: (r: string) => `需【${r}】境`,
    weaponCostShort: '灵石不足',
    // M11 斩妖（#35）
    slayTitle: '妖 兽 拦 路',
    slayTip: '连续点按斩击妖兽，气血耗尽则妖兽遁走',
    slayWin: '斩 妖 成 功',
    slayLose: '妖兽遁走，血战无功',
    slayMorale: '战意昂扬 · 事件所得灵石增幅一成五',
    slayRetry: '再 战',
    // M11 论武（#36）
    pkPageTitle: '论武 · 切磋',
    pkRandom: '随机切磋',
    pkFriend: '约人切磋',
    pkRemaining: (n: number, total: number) => `今日切磋 ${total - n}/${total} 场`,
    pkExhausted: '今日切磋帖已用尽，明日再来',
    pkStreak: (n: number) => `连胜 ×${n}`,
    pkRecord: (w: number, l: number, best: number) => `战绩 ${w} 胜 ${l} 负 · 最高连胜 ${best}`,
    pkOppPower: (p: number) => `战力约 ${p}`,
    pkChargeBtn: '蓄力 · 观广告',
    pkChargeInfo: (n: number, pct: number) => `蓄力 ${n}/10 · 本次攻防 +${pct}%`,
    pkChargeMaxed: '蓄力已满，战意如虹',
    pkStart: '开 战',
    pkWinTitle: '切磋获胜',
    pkLoseTitle: '切磋落败',
    pkNoReward: '落败无所得，胜败乃修行常事',
    pkChargeRetry: '蓄力再战 · 观广告',
    pkGiveUp: '收手言和',
    pkRematchHint: (n: number) => `每观一支广告攻防 +10%（本场已用 ${n}/10），再战同一对手`,
    pkWinRewardTitle: '切磋得胜 · 天道酬勤',
    pkFriendShared: '切磋帖已发出，等道友应战（先与影修过招）',
    pkFriendHint: '向道友发起切磋，以武会友',
    // M11b 细化：个人属性页
    playerPageTitle: '道 体',
    playerForgeLine: (lv: number, cost: string) => `锻体 ${lv} 重${cost ? ` · 下级 ${cost} 灵石` : ' · 圆满'}`,
    playerWeapon: '当前法器',
    playerWeaponNone: '尚未佩剑 · 前往法器阁选购',
    playerGoWeapon: '前往法器阁',
    playerFortune: '福 禄',
    playerFortuneMonthly: (d: number) => `月卡特权 · 剩余 ${d} 天`,
    playerFortuneMonthlyNone: '月卡未激活（内购待版号）',
    playerFortuneTicket: (n: number) => `修真宝盒券 ×${n}`,
    playerFortuneGift: (used: boolean) => `每日仙缘 · ${used ? '今日已领' : '今日未领'}`,
    playerFortuneLingen: (pct: number) => `灵根图鉴 · 修为加成 +${pct}%`,
    // M11b 细化：论武蓄力与斗法演出
    pkChargeStage: (cn: string) => `蓄力${cn}重`,
    pkChargeStageZero: '蓄力未启 · 观广告凝聚战意',
    pkWinOdds: (p: number) => `胜率预估 ${p}%`,
    pkWinOddsNext: (p: number) => `再蓄一支 +${p}%`,
    pkChargeFull: '蓄力十重 · 战意如虹',
    pkFighting: '斗法进行中…',
    // M13 炼丹淬体 / 福禄炼制（#39–#41）
    alchemyTitle: '炼丹淬体',
    alchemyHint: '吞服灵丹，温养四维本体资质',
    alchemyStatWisdom: '智力',
    alchemyStatSpeed: '速度',
    alchemyStatForging: '淬体',
    alchemyStatFate: '机缘',
    alchemyStatWisdomDesc: '修为获取 +',
    alchemyStatSpeedDesc: '灵气雨移速 +',
    alchemyStatForgingDesc: '战斗减伤 +',
    alchemyStatFateDesc: '突破成功率 +',
    alchemyCraft: '炼 制',
    alchemyCrafted: '已炼满',
    alchemyLocked: (r: string) => `需【${r}】境`,
    alchemyCost: (ls: number, mat: number) => mat > 0 ? `${ls} 灵石 + 灵材×${mat}` : `${ls} 灵石`,
    alchemyMaxed: '此品丹药已炼满',
    alchemyNoMaterial: '灵材不足，开箱/历练/斩妖可得',
    alchemyNoLingshi: '灵石不足',
    fortuneTitle: '福禄炼制',
    fortuneHint: '福泽加身，攻防永固',
    fortuneAtkDef: (atk: number, def: number) => `攻击 +${atk} · 防御 +${def}`,
    fortuneCraft: '炼 制',
    fortuneCrafted: (n: number, max: number) => `${n}/${max} 次`,
    fortuneMaxed: '此品福禄已炼满',
    materialTitle: '灵材',
    materialNone: '暂无灵材',
    materialCount: (n: number) => `灵材 ×${n}`,
} as const;
