/** PRD 第四章：弹窗与提示文案全集（合规改写，无赌博词汇）。代码统一引用本表，禁止散落硬编码。 */
export const TEXTS = {
    boxShake: '天地仙缘汇聚，静待揭晓',
    boxNormal: '获得些许修为，稳步修行',
    boxRare: '天降机缘，灵根增益！',
    boxBreakthroughChance: '感应到突破契机，可尝试冲击下一境界！',
    boxDisaster: '心魔侵扰，修为受损。',
    keepReward: '收下本次所得，暂作休整',
    seekAgain: '继续探寻仙缘，再试一次',
    seekLimit: '今日求索次数已用尽，先休整',
    rainOpen: '天道降下灵雨，把握机缘，躲避劫扰',
    rainImmortal: '完美接引灵雨，道心稳固！',
    breakthroughSuccess: (realm: string) => `境界晋升，踏入【${realm}】！`,
    breakthroughFail: '心魔干扰，突破未果，修为受损。',
    pityTriggered: '天道眷顾，获得稀有机缘。',
    lingshiNotEnough: '灵石不足，可观看广告获取灵石',
    lingshiAidRemain: (n: number, total: number) => `今日灵石救济剩余 ${n}/${total} 次`,
    lingshiAidExhausted: '今日救济次数已用尽，明日再来',
    rainTip: '滑动操控角色，接引灵雨，规避劫扰',
    quitRainConfirm: '退出则本次突破终止，机缘将受损，确定退出？',
    doubleXiuweiBtn: '修为加倍',
    protectBtn: '渡劫护道',
    purifyBtn: '净化劫雨',
    dailyGiftBtn: '每日仙缘',
    adSimTitle: '模拟激励广告',
    probabilityPublic: '概率公示',
    realmMax: '已达化神大圆满，前路自在心中',
    // 灵根图鉴（PRD 页面5）
    collectionHint: '收集灵根碎片，解锁道体外观',
    collectionCompose: '合 成',
    collectionComposed: '已解锁',
    collectionLocked: '未解锁',
    // 仙府商店（PRD 页面6）
    shopIapNotice: '内购功能审核中，暂未开放',
    shopIapOnlyVisual: '所有外观仅视觉效果，不改变修行概率',
    shopBuyBtn: '购 买',
    shopUnavailable: '暂未开放',
    // 设置（PRD 页面7）
    settingsSound: '音效',
    settingsBgm: '背景音乐',
    settingsProbability: '概率公示',
    settingsUserAgreement: '用户协议',
    settingsPrivacy: '隐私政策',
    probabilityTitle: '概率公示',
    agreementTitle: '用户协议',
    privacyTitle: '隐私政策',
    agreementPending: '正式协议文本上线前由运营补充（抖音审核必需）。',
    privacyPending: '正式隐私政策文本上线前由运营补充（抖音审核必需）。',
    // M7 交互深化（数值假设 #20–#26）
    resonateHint: '按住蓄力，光标居中时松手可引灵气共鸣',
    resonatePlainHint: '快速点击则直接开启',
    resonateSuccess: '灵气共鸣！所得增幅一成五',
    resonateSkip: '直接开启',
    chargeTitle: '引灵入匣',
    tripleTitle: '圆满三连',
    tripleHint: '依序点亮灵光符文，可获得天道赠礼',
    tripleSkip: '跳过',
    tripleLayer: (n: number) => `圆满 ×${n}`,
    tripleFull: '修行圆满，天道赠礼！',
    waveYunyu: '蕴雨 · 天地初霁',
    waveLingchao: '灵雨潮 · 机缘暴涨',
    waveJieyun: '劫云压顶 · 谨慎走位',
    comboFloat: (n: number) => `连击 ×${n}`,
    magnetBtn: '聚灵咒',
    magnetActive: '聚灵生效中',
    magnetUsed: '本局聚灵咒已用完',
    scoreLine: (score: number, combo: number) => `渡劫评分 ${score} · 最大连击 ×${combo}`,
    perfectStars: '★ ★ ★',
    // M8 修行日常（数值假设 #27–#29）
    questPageTitle: '修行任务',
    questActivity: (n: number) => `活跃度 ${n}/100`,
    questDone: '已完成',
    questChestClaim: '领 取',
    questChestClaimed: '已 领',
    questChestLocked: (at: number) => `需 ${at} 活跃度`,
    questRewardTicket: '修真宝盒券 ×1',
    illusionTitle: '秘境试炼',
    illusionOpen: '幻由心生，道心不灭——斩尽心魔',
    illusionTip: '15 秒强化灵雨：无清雨、劫雨更疾。得分越高，天道赏赐越厚',
    illusionEnter: '进入秘境',
    illusionEnterAd: '再战一局',
    illusionAgainCost: '消耗 1 体力开始下一局',
    illusionNone: '体力不足，休息片刻再来（15 分钟回复 1 点）',
    illusionScoreLine: (score: number, best: number) => `幻境得分 ${score} · 今日最佳 ${best}`,
    illusionNoTier: '未达奖励档位（需 60 分），再接再厉',
    illusionTierReward: (t: string) => `达成【${t}】，天道赏赐：`,
    /** M14 秘境：体力与主题（#42） */
    trialStaminaLine: (cur: number, max: number) => `体力 ${cur}/${max}`,
    trialThemeLine: (name: string, desc: string) => `今日秘境 · ${name}：${desc}`,
    trialStreakLine: (streak: number, mult: number) => `当前连胜 ${streak} 连 · 奖励倍率 ×${mult}`,
    trialReviveTitle: '道心护持',
    trialReviveDesc: (streak: number) => `本局未达 60 分，${streak} 连即将中断——观广告可保留连胜`,
    trialReviveBtn: '道心护持 · 保留连胜',
    trialReviveDone: '护持成功 · 连胜保留',
    trialReviveGiveUp: '不复护持',
    trialReviveGone: '连胜已中断',
    trialDoubleBtn: '奖励翻倍 · 广告',
    trialDoubled: '已翻倍',
    trialRefillBtn: '观广告 · 补体力',
    trialSeasonLine: (name: string, score: number, bestName: string) => `本赛季「${name}」${score} 分 ｜ 历史最高「${bestName}」`,
    trialClaimBtn: (name: string) => `领上赛季周奖 · ${name}`,
    trialClaimed: '上赛季周奖已领取',
    trialNoClaim: '周奖下周一随赛季结算开放领取',
    // ---------- M15 妖径（#47，历练重构） ----------
    trailPageTitle: (ch: string) => `妖径 · ${ch}`,
    trailLayerNum: (n: number) => `第 ${n} 层`,
    trailChapterDone: (n: number) => `本章已通 ${n}/10 层`,
    trailBossTag: '妖王',
    trailTypeBattle: '斗妖',
    trailTypePuzzle: '拼图',
    trailTypeMatch3: '三消',
    trailCleared: '已通 · 可重刷',
    trailLocked: '未解锁',
    trailRepeatLeft: (l: number, t: number) => `今日重刷产出剩余 ${l}/${t} 次`,
    trailHintLine: '通关当前层解锁下一层 · 重刷已通层有小额产出',
    trailLockedToast: '先通关前面的层',
    trailEnterToast: (name: string) => `${name} 拦路！点按斩击`,
    trailQuitTitle: '离开妖径',
    trailQuitLine: '退出将放弃本层进度，确定离开？',
    trailReviveTitle: '妖影反噬',
    trailReviveLine: '气血耗尽！看广告回魂（回复五成气血，继续本层战斗）',
    trailReviveBtn: '回魂再战 · 广告',
    trailRevived: '回魂成功！妖影为之一滞',
    trailGiveUpBtn: '力竭而退',
    trailResultWin: '降妖成功',
    trailResultLose: '妖影反噬',
    trailKindFirst: '首通大礼',
    trailKindRepeat: '重刷产出',
    trailKindGated: '今日重刷产出已用尽（可继续挑战，零收益）',
    trailChapterGift: '章节大礼！',
    trailNextLayer: '进军下一层',
    trailRetry: '再战此层',
    trailBackTrail: '返回妖径',
    trailWinFx: '斩！',
    // M16 妖像拼图
    trailPuzzlePage: (name: string) => `封印拼图 · ${name}`,
    trailPuzzleHintLine: '点选两块交换 · 归位即封印',
    trailPuzzleHp: '封印',
    trailPuzzleTime: '时辰',
    trailPuzzlePeek: '凝神一瞥',
    trailPuzzlePeekAd: '凝神一瞥 · 广告',
    trailPuzzlePeeked: '凝神一瞥！记住原貌',
    trailPuzzleNoPeek: '今日凝神次数已用尽',
    trailPuzzleReviveTitle: '封印未成',
    trailPuzzleReviveLine: '时限已尽！看广告凝神续时（+15 秒，继续封印）',
    trailPuzzleWinFx: '封！',
    trailPuzzleSwapLocked: '此块已归位封死',
    // M17 妖影三消
    trailMatch3Page: (name: string) => `妖影三消 · ${name}`,
    trailMatch3HintLine: '交换相邻妖影凑三连 · 连锁破妖',
    trailMatch3Hp: '妖 血',
    trailMatch3Steps: (n: number) => `步数 ${n}`,
    trailMatch3Shuffle: '妖风洗牌 · 广告',
    trailMatch3Shuffled: '妖风骤起，妖影重排！',
    trailMatch3ReviveTitle: '步数用尽',
    trailMatch3ReviveLine: '未能破妖！看广告续步（+5 步，继续挑战）',
    trailMatch3WinFx: '破！',
    trailMatch3Quit: '继续破妖',
    // ---------- M22 剑冢试炼（#48） ----------
    towerTitle: '剑冢试炼',
    towerBannerSub: (floor: number, atk: string) => `最高第 ${floor} 层 · 剑气 ${atk}`,
    towerPageTitle: '剑 冢',
    towerBlurb: '万剑埋骨之地，剑气无涯，唯淬剑者能上',
    towerSwordAtk: '剑气',
    towerLevel: (n: number) => `淬剑 ${n} 级`,
    towerCrystal: '煞晶',
    towerCost: (c: string) => `下次淬剑 · ${c}`,
    towerToNextFloor: (k: number, floor: number) => k <= 0 ? `已可破第 ${floor} 层` : `距第 ${floor} 层还需约 ${k} 级淬剑`,
    towerForge1: '淬 ×1',
    towerForge10: '淬 ×10',
    towerForgeMax: '淬 满',
    towerForgeNone: '煞晶不足',
    towerForgeDone: (n: number) => n > 0 ? `淬剑 ${n} 级！剑气上涨` : '煞晶不足，先入冢积攒',
    towerEnter: (f: number) => `入冢 · 第 ${f} 层起`,
    towerDailyLine: (a: number, b: number, c: number, d: number, e: number, f: number) =>
        `今日回灌 灵石 ${a}/${b} · 灵材 ${c}/${d} · 修为 ${e}/${f}`,
    towerScaleHint: (best: number, from: number) => `层刻度 · 最高 ${best} · 本局自 ${from} 层起`,
    towerFloorTitle: (f: number) => `第 ${f} 层`,
    towerGang: '剑 罡',
    towerMonsterHp: '妖 血',
    towerChargeBtn: '凝神一击',
    towerChargeHint: '红环亮起时点击「凝神一击」打断蓄力',
    towerChargeMiss: '错失时机！',
    towerChargeHit: '凝神一击！',
    towerTutorialTitle: '剑冢初探',
    towerTutorialLines: [
        '此冢无底：淬剑愈深，剑气愈盛，层数永无上限。',
        '下妖蓄力时红环亮起 —— 点「凝神一击」打断它，',
        '既重创妖物，也回一口剑罡。第一层，放手去试。',
    ],
    towerTutorialBtn: '入冢',
    towerChargePrompt: '红环亮了 · 点它！',
    towerQuit: '收兵',
    towerQuitTitle: '收兵回山',
    towerQuitLine: '已赚煞晶全部保留，退出后可再次入冢，确定收兵？',
    towerQuitBack: '继续战斗',
    towerReviveTitle: '剑罡溃散',
    towerReviveLine: '剑罡耗尽！看广告回魂（剑罡回满，本局剑气 ×1.25）',
    towerReviveBtn: '回魂再战 · 广告',
    towerReviveLeft: (n: number) => `本局回魂剩余 ${n} 次`,
    towerRevived: '回魂！剑气暴涨',
    towerGiveUpBtn: '收兵返回',
    towerForgePanel: (c: string) => `淬剑 · ${c} 煞晶`,
    towerResultWin: '剑冢收兵',
    towerResultDeepest: (f: number, best: number) => `本局最深 第 ${f} 层 · 最高纪录 第 ${best} 层`,
    towerResultNewBest: '新纪录！',
    towerResultCrystal: (c: string) => `本局煞晶 +${c}`,
    towerResultLevel: (a: number, b: number) => `淬剑等级 ${a} → ${b}`,
    towerResultMainline: '主线回灌',
    towerResultCapped: '今日回灌额度已用尽（明日翻新）',
    towerResultRevives: (n: number) => `本局回魂 ${n} 次`,
    towerResultAgain: '再入剑冢',
    towerResultHome: '返回主页',
    boxTicketBtn: '券 开 启',
    // M9a 论道与成就
    ludaoPageTitle: '论 道',
    ludaoTabRank: '排行',
    ludaoTabIllusion: '秘境',
    ludaoTabAchieve: '成就',
    rankRealmName: '境界榜',
    rankIllusionName: '幻境周榜',
    rankTribName: '渡劫评分榜',
    rankEmpty: '广结道友，共赴大道',
    rankYou: (v: string) => `你　　${v}`,
    rankGoal: (v: string) => `目标　${v}`,
    rankGoalLine: (name: string, v: string) => `${name}　${v}`,
    achieveClaim: '领 取',
    achieveClaimed: '已 领',
    achieveNew: (name: string) => `成就达成 · ${name}`,
    // M9c 收尾（PRD 2.4 分享 / 境界外观展示）
    shareBreakthrough: (realm: string) => `渡劫成功！我已踏入【${realm}】境，道友请留步~`,
    shareRealmUnlock: (realm: string) => `我在《凡人开仙缘》的道行已达【${realm}】，快来一起修仙！`,
    shareUnavailable: '分享功能仅在抖音端可用',
    realmLookTitle: '境界外观',
    realmLookReached: '当前境界 · 已解锁',
    realmLookLocked: (r: string) => `突破至【${r}】境解锁`,
    // M11 捏人开局（#32）
    profileTitle: '拜 入 仙 门',
    profileHint: '择一道体，取一道号，此生修行皆以此为凭',
    profileMale: '男 修',
    profileFemale: '女 修',
    profileNameHint: '道号（2~6 字）',
    profileRandomName: '随机道号',
    profileConfirm: '踏 入 仙 途',
    profileNameInvalid: '道号需 2~6 个字',
    // M11 攻防属性（#33）
    statAtk: '攻击',
    statDef: '防御',
    statPower: '战力',
    forgingTitle: '锻体',
    forgingLevel: (lv: number) => `锻体 ${lv} 重`,
    forgingMax: '锻体已至圆满',
    // M11 法器阁（#34）
    weaponTitle: '法 器 阁',
    weaponOwned: '已佩',
    weaponEquipped: '当前佩用',
    weaponBuy: '购 入',
    weaponLocked: (r: string) => `需【${r}】境`,
    weaponCostShort: '灵石不足',
    // M11 斩妖（#35）
    slayTitle: '妖 兽 拦 路',
    slayTip: '连续点按斩击妖兽，气血耗尽则妖兽遁走',
    slayWin: '斩 妖 成 功',
    slayLose: '妖兽遁走，血战无功',
    slayMorale: '战意昂扬 · 事件所得灵石增幅一成五',
    slayRetry: '再 战',
    // M11 论武（#36）
    pkPageTitle: '论武 · 切磋',
    pkRandom: '随机切磋',
    pkFriend: '约人切磋',
    pkRemaining: (n: number, total: number) => `今日切磋 ${total - n}/${total} 场`,
    pkExhausted: '今日切磋帖已用尽，明日再来',
    pkStreak: (n: number) => `连胜 ×${n}`,
    pkRecord: (w: number, l: number, best: number) => `战绩 ${w} 胜 ${l} 负 · 最高连胜 ${best}`,
    pkOppPower: (p: number) => `战力约 ${p}`,
    pkChargeBtn: '蓄力 · 观广告',
    pkChargeInfo: (n: number, pct: number) => `蓄力 ${n}/10 · 本次攻防 +${pct}%`,
    pkChargeMaxed: '蓄力已满，战意如虹',
    pkStart: '开 战',
    pkWinTitle: '切磋获胜',
    pkLoseTitle: '切磋落败',
    pkNoReward: '落败无所得，胜败乃修行常事',
    pkChargeRetry: '蓄力再战 · 观广告',
    pkGiveUp: '收手言和',
    pkRematchHint: (n: number) => `每观一支广告攻防 +10%（本场已用 ${n}/10），再战同一对手`,
    pkWinRewardTitle: '切磋得胜 · 天道酬勤',
    pkFriendShared: '切磋帖已发出，等道友应战（先与影修过招）',
    pkFriendHint: '向道友发起切磋，以武会友',
    // M11b 细化：个人属性页
    playerPageTitle: '道 体',
    playerForgeLine: (lv: number, cost: string) => `锻体 ${lv} 重${cost ? ` · 下级 ${cost} 灵石` : ' · 圆满'}`,
    playerWeapon: '当前法器',
    playerWeaponNone: '尚未佩剑 · 前往法器阁选购',
    playerGoWeapon: '前往法器阁',
    playerFortune: '福 禄',
    playerFortuneMonthly: (d: number) => `月卡特权 · 剩余 ${d} 天`,
    playerFortuneMonthlyNone: '月卡未激活（内购待版号）',
    playerFortuneTicket: (n: number) => `修真宝盒券 ×${n}`,
    playerFortuneGift: (used: boolean) => `每日仙缘 · ${used ? '今日已领' : '今日未领'}`,
    playerFortuneLingen: (pct: number) => `灵根图鉴 · 修为加成 +${pct}%`,
    // M11b 细化：论武蓄力与斗法演出
    pkChargeStage: (cn: string) => `蓄力${cn}重`,
    pkChargeStageZero: '蓄力未启 · 观广告凝聚战意',
    pkWinOdds: (p: number) => `胜率预估 ${p}%`,
    pkWinOddsNext: (p: number) => `再蓄一支 +${p}%`,
    pkChargeFull: '蓄力十重 · 战意如虹',
    pkFighting: '斗法进行中…',
    // M13 炼丹淬体 / 福禄炼制（#39–#41）
    alchemyTitle: '炼丹淬体',
    alchemyHint: '吞服灵丹，温养四维本体资质',
    alchemyStatWisdom: '智力',
    alchemyStatSpeed: '速度',
    alchemyStatForging: '淬体',
    alchemyStatFate: '机缘',
    alchemyStatWisdomDesc: '修为获取 +',
    alchemyStatSpeedDesc: '灵气雨移速 +',
    alchemyStatForgingDesc: '战斗减伤 +',
    alchemyStatFateDesc: '突破成功率 +',
    alchemyCraft: '炼 制',
    alchemyCrafted: '已炼满',
    alchemyLocked: (r: string) => `需【${r}】境`,
    alchemyCost: (ls: number, mat: number) => mat > 0 ? `${ls} 灵石 + 灵材×${mat}` : `${ls} 灵石`,
    alchemyMaxed: '此品丹药已炼满',
    alchemyNoMaterial: '灵材不足，开箱/历练/斩妖可得',
    alchemyNoLingshi: '灵石不足',
    fortuneTitle: '福禄炼制',
    fortuneHint: '福泽加身，攻防永固',
    fortuneAtkDef: (atk: number, def: number) => `攻击 +${atk} · 防御 +${def}`,
    fortuneCraft: '炼 制',
    fortuneCrafted: (n: number, max: number) => `${n}/${max} 次`,
    fortuneMaxed: '此品福禄已炼满',
    materialTitle: '灵材',
    materialNone: '暂无灵材',
    materialCount: (n: number) => `灵材 ×${n}`,

    // ---------- #49 首日体验：首战保护（天道庇佑） ----------
    /** 首战横幅（渡劫页顶部常驻）+ 引导条主文案（进入渡劫前就已可见） */
    firstBattleBanner: '首次渡劫 · 天道庇佑',
    /** 结算页标注（首战必成） */
    firstBattleResult: '天道庇佑 · 首战必成',

    // ---------- #49 首日体验：首页「今日引导条」（语境 CTA 四态） ----------
    // 优先级 1：机缘够 → 渡劫（最高情绪）
    homeGuideBreak: (realm: string) => `冲击境界 · ${realm}`,
    homeGuideBreakSub: (cur: number, need: number) => `机缘 ${cur}/${need} · 渡劫在即`,
    // 优先级 1'：首战（同去渡劫，但讲成「天道庇佑」设定，见 #49 A3）
    homeGuideFirstSub: (cur: number, need: number) => `机缘 ${cur}/${need} · 首战必成`,
    // 优先级 2：秘境体力有剩余 → 15 秒短局（首日唯一「立刻能玩」的内容）
    homeGuideTrial: '秘境试炼 · 15 秒',
    homeGuideTrialSub: (stamina: number, theme: string) => `体力 ${stamina} · 今日【${theme}】`,
    // 优先级 3：灵石够开箱 → 攒机缘
    homeGuideBox: '开仙缘宝盒',
    homeGuideBoxSub: (lingshi: number, cur: number, need: number) => `灵石 ${lingshi} · 机缘 ${cur}/${need}`,
    // 优先级 4：都不满足 → 领机遇（复用每日仙缘）
    homeGuideGift: '领取机遇',
    homeGuideGiftSub: '灵石不足，看广告得 300',
} as const;
